### ISSUE TITLE
Consideration on Enumeration

### ISSUE THREAD

**Issue by haomianzheng** [younglee-ietf/actn-wson-flexi-grid#2]
It is suggested to change the enumeration format to identity, for future extensions. 

Old: 
 typedef FEC {
    type enumeration {
	  enum reed-solomon {
		  description "Reed-Solomon error correction";
	  }
	  enum hamming-code{
		  description "Hamming Code error correction";
	  }
	  enum golay{
		  description "Golay error correction";
	  }
    }

New

 identity FEC {
    description "base identity for different types of FEC"; 
}

identity reed-solomon {
    base FEC;
    description "Reed-Solomon error correction";
}

identity hamming-code{
    base FEC;
    description "Hamming Code error correction";
}
	  
identity golay{
    base FEC; 
    description "Golay error correction";
	  }

**Comment by haomianzheng** [comment]
Note: this is an issue in ietf-wson-impairment-topology.

**Comment by younglee-ietf** [comment]
Issue resolved. Updated with identityref for FEC and Modulation type.
